### PR TITLE
Detect change via rename

### LINKED ISSUE #7: NOT FIXED: Not refreshing on reload of cshtml file
Hi @madskristensen,

Firstly we appreciate the effort you make towards all your extensions. 

This issue keeps getting closed, even though it doesn't always get fully fixed:
It was first noted here:
https://github.com/madskristensen/BrowserReloadOnSave/issues/5

Then the same type of issue was opened here:
https://github.com/madskristensen/BrowserReloadOnSave/issues/6

In both cases the issue gets closed without someone verifying that it actually is fixed

Just to recap:
CSHTML - **NOT WORKING**
CSS - **WORKING**
JS - **WORKING**

Again I'll open the invitation to you, if you would like to remote into my computer and test this out yourself you are welcome to, let's try and get this issue resolved

**UPDATE**
I finally got the the browser to reload on save for .cshtml

The issue is that my projects are on my **D drive** under **D:\Programming\Projects**
I then moved one of my projects onto the **C drive** and it instantly worked

I'm not sure why it doesn't work on another drive as yet... I'll keep investigating, could be a permission problem?

### PR DESCRIPTION
**Pull request by ghost**
Fixes https://github.com/madskristensen/BrowserReloadOnSave/issues/7 and https://github.com/madskristensen/BrowserReloadOnSave/issues/17 (duplicate)

### CODE REVIEW

**Comment by madskristensen** [comment]
thanks

**Comment by ghost** [comment]
Awesome! Will you publish an update on marketplace.visualstudio.com?

**Comment by madskristensen** [comment]
Grab the CI build. It's the same one i'll upload when I have time. http://vsixgallery.com/extension/2d8aa02a-8810-421f-97b9-86efc573fea3/

**Comment by Kavik00** [comment]
You should upload this fix to the VS Extensions.  The version currently on there is 1.1.27 vs 1.1.30,
I've been banging my head against the wall for six months until finally tonight, I found this post!  😂🤣

**Comment by doggy8088** [comment]
@madskristensen Can you publish new version to the [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.BrowserReloadonSave)?

**Comment by madskristensen** [comment]
Done

**Pull request merged**
